name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish release
    runs-on: macOS-latest # it has NDK installed
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.0
      - name: Build project
        run: ./gradlew clean build
        env:
          VERSION: ${{ github.ref }}
      - run: |
          assetsAAR=$(find . -name *release.aar | while read -r asset ; do echo "-a $asset" ; done)
          VERSION=$(echo $VERSION | cut -d'/' -f3)
          tag_name="${GITHUB_REF##*/}"
          hub release create ${assetsAAR} -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
